### ISSUE TITLE
Blank window and 100% CPU usage

### ISSUE THREAD

**Issue by haasn** [mikesart/gpuvis#13]
Not entirely sure what's going on here. Other OpenGL applications work fine; but `gpuvis` has stopped working for me.

The annoying thing is that it's been quite some time since I last used gpuvis. I already know it's not a gpuvis regression (I can go back hundreds of commits and the behavior doesn't change, including to the commit that I was using previously without any issues).

glxinfo: https://0x0.st/sKso.txt
strace: https://0x0.st/sKsH.log

I tried using apitrace, but got unexpected behavior:
```
$ apitrace trace ./gpuvis
apitrace: loaded into /usr/bin/apitrace
apitrace: unloaded from /usr/bin/apitrace
apitrace: loaded into /home/nand/dev/gpuvis/build/gpuvis
apitrace: redirecting dlopen("libGL.so.1", 0x102)
apitrace: tracing to /home/nand/dev/gpuvis/build/gpuvis.trace
apitrace: redirecting dlopen("libGL.so.1", 0x102)
apitrace: redirecting dlopen("libGL.so.1", 0x102)
apitrace: redirecting dlopen("libGL.so.1", 0x101)
apitrace: warning: glVertexAttribPointer: call will be faked due to pointer to user memory (https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#tracing)
apitrace: warning: caught signal 11
apitrace: ignoring exception while tracing
/usr/bin/../lib64/apitrace/wrappers/glxtrace.so+0x2a88fc
/lib64/libpthread.so.0+0x14fff
/lib64/libc.so.6+0xaca94
/usr/bin/../lib64/apitrace/wrappers/glxtrace.so+0x2a81b4
/usr/bin/../lib64/apitrace/wrappers/glxtrace.so+0x2a5568
/usr/bin/../lib64/apitrace/wrappers/glxtrace.so: glDrawElements+0x1eb
./gpuvis: _Z32ImGui_ImplSdlGL3_RenderDrawListsP10ImDrawData+0x57d
./gpuvis: _ZN5ImGui6RenderEv+0x6b0
./gpuvis+0x187a19
./gpuvis: main+0x3f3
/lib64/libc.so.6: __libc_start_main+0xfc
./gpuvis: _start+0x29
?
apitrace: info: taking default action for signal 11
# command exited with return code 139
```
It immediately exited after printing those messages. The resulting trace is at https://0x0.st/sKsX.trace

If I try `perf top` to view what it's spending time doing, I get:
```

   PerfTop:    3895 irqs/sec  kernel: 0.6%  exact:  0.0% [4000Hz cycles],  (target_pid: 27564)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                               

    61.82%  gpuvis                 [.] ImFontAtlas::GetTexDataAsRGBA32
     4.55%  libfreetype.so.6.15.0  [.] gray_render_line
     3.02%  libfreetype.so.6.15.0  [.] gray_record_cell
     2.43%  gpuvis                 [.] stbrp__skyline_find_min_y
     2.29%  libc-2.26.so           [.] __memset_sse2_unaligned_erms
     1.96%  libfreetype.so.6.15.0  [.] gray_hline
     1.68%  libfreetype.so.6.15.0  [.] af_glyph_hints_reload
     1.31%  libfreetype.so.6.15.0  [.] gray_convert_glyph
     1.16%  libfreetype.so.6.15.0  [.] gray_set_cell
     1.14%  libfreetype.so.6.15.0  [.] TT_Load_Simple_Glyph
     1.08%  libfreetype.so.6.15.0  [.] af_latin_hints_compute_segments
     0.89%  libfreetype.so.6.15.0  [.] af_latin_hints_apply
     0.85%  gpuvis                 [.] stbrp__skyline_find_best_pos
     0.68%  libfreetype.so.6.15.0  [.] gray_render_conic
     0.67%  libfreetype.so.6.15.0  [.] FT_Outline_Get_CBox
     0.62%  libfreetype.so.6.15.0  [.] TT_RunIns
     0.62%  libfreetype.so.6.15.0  [.] af_latin_hints_link_segments
     0.56%  libfreetype.so.6.15.0  [.] af_latin_hints_compute_edges
     0.50%  libfreetype.so.6.15.0  [.] FT_Outline_Decompose
     0.45%  libfreetype.so.6.15.0  [.] af_glyph_hints_align_weak_points
     0.42%  libfreetype.so.6.15.0  [.] tt_cmap4_char_map_binary
     0.35%  libc-2.26.so           [.] __memmove_sse2_unaligned_erms
     0.32%  libfreetype.so.6.15.0  [.] af_glyph_hints_align_strong_points
     0.31%  libfreetype.so.6.15.0  [.] load_truetype_glyph
     0.27%  libfreetype.so.6.15.0  [.] FT_DivFix
     0.27%  libfreetype.so.6.15.0  [.] af_glyph_hints_save.isra.5
     0.26%  libfreetype.so.6.15.0  [.] af_autofitter_load_glyph
     0.26%  libfreetype.so.6.15.0  [.] FT_Load_Glyph
     0.25%  libc-2.26.so           [.] _int_free
     0.21%  libc-2.26.so           [.] malloc
     0.19%  libfreetype.so.6.15.0  [.] ft_smooth_render_generic
     0.18%  gpuvis                 [.] (anonymous namespace)::FreeTypeFont::BlitGlyph
     0.18%  libc-2.26.so           [.] _int_malloc
     0.18%  libc-2.26.so           [.] cfree@GLIBC_2.2.5
     0.18%  libfreetype.so.6.15.0  [.] TT_Load_Glyph
     0.18%  libfreetype.so.6.15.0  [.] ft_mem_qrealloc
     0.17%  libc-2.26.so           [.] tcache_get
     0.17%  libfreetype.so.6.15.0  [.] FT_Outline_Get_Orientation
     0.16%  libfreetype.so.6.15.0  [.] af_iup_interp.part.11
     0.16%  libfreetype.so.6.15.0  [.] FT_Outline_Translate
     0.15%  gpuvis                 [.] ImGuiFreeType::BuildFontAtlas
     0.13%  libfreetype.so.6.15.0  [.] af_axis_hints_new_edge
     0.13%  libfreetype.so.6.15.0  [.] FT_Glyph_To_Bitmap
     0.12%  libfreetype.so.6.15.0  [.] af_face_globals_new
     0.11%  libfreetype.so.6.15.0  [.] tt_face_get_metrics
     0.11%  libfreetype.so.6.15.0  [.] tt_loader_init
     0.11%  gpuvis                 [.] ImFontAtlasBuildRenderDefaultTexData
     0.11%  libc-2.26.so           [.] tcache_put
     0.10%  libfreetype.so.6.15.0  [.] TT_Load_Glyph_Header
     0.10%  libfreetype.so.6.15.0  [.] ft_mem_free
     0.09%  libfreetype.so.6.15.0  [.] gray_conic_to
     0.09%  libfreetype.so.6.15.0  [.] FT_MulDiv
     0.09%  libfreetype.so.6.15.0  [.] FT_Stream_ReadUShort
     0.09%  libfreetype.so.6.15.0  [.] gray_raster_render
     0.09%  libfreetype.so.6.15.0  [.] _iup_worker_interpolate.part.51
     0.09%  gpuvis                 [.] ImFont::AddGlyph
     0.09%  gpuvis                 [.] stbrp_pack_rects
     0.09%  libfreetype.so.6.15.0  [.] FT_Get_Next_Char
     0.08%  libc-2.26.so           [.] qsort
     0.08%  libfreetype.so.6.15.0  [.] gray_line_to
     0.08%  gpuvis                 [.] (anonymous namespace)::FreeTypeFont::CalcGlyphInfo
     0.08%  libfreetype.so.6.15.0  [.] ft_mem_alloc
     0.08%  libc-2.26.so           [.] memcpy@GLIBC_2.2.5
     0.08%  libfreetype.so.6.15.0  [.] tt_get_metrics
```

And a gdb backtrace from the busy thread:
```
^C
Thread 1 "gpuvis" received signal SIGINT, Interrupt.
0x00007f09d3d0c80c in af_glyph_hints_align_strong_points (hints=hints@entry=0x7ffdd1ebdb10, dim=dim@entry=AF_DIMENSION_VERT) at /usr/src/debug/media-libs/freetype-2.8.1/freetype-2.8.1/src/autofit/afhints.c:1328
1328	              if ( edges[nn].fpos >= u )
(gdb) bt
#0  0x00007f09d3d0c80c in af_glyph_hints_align_strong_points (hints=hints@entry=0x7ffdd1ebdb10, dim=dim@entry=AF_DIMENSION_VERT) at /usr/src/debug/media-libs/freetype-2.8.1/freetype-2.8.1/src/autofit/afhints.c:1328
#1  0x00007f09d3d6ce1e in af_latin_hints_apply (glyph_index=<optimized out>, hints=0x7ffdd1ebdb10, outline=<optimized out>, metrics=<optimized out>) at /usr/src/debug/media-libs/freetype-2.8.1/freetype-2.8.1/src/autofit/aflatin.c:3552
#2  0x00007f09d3d6e962 in af_loader_load_glyph (load_flags=<optimized out>, glyph_index=74, face=<optimized out>, module=<optimized out>, loader=0x7ffdd1ebda90) at /usr/src/debug/media-libs/freetype-2.8.1/freetype-2.8.1/src/autofit/afloader.c:429
#3  af_autofitter_load_glyph (module=<optimized out>, slot=<optimized out>, size=<optimized out>, glyph_index=74, load_flags=<optimized out>) at /usr/src/debug/media-libs/freetype-2.8.1/freetype-2.8.1/src/autofit/afmodule.c:561
#4  0x00007f09d3d17165 in FT_Load_Glyph (face=0x5575072d8610, glyph_index=74, load_flags=<optimized out>) at /usr/src/debug/media-libs/freetype-2.8.1/freetype-2.8.1/src/base/ftobjs.c:757
#5  0x00005575067ac052 in (anonymous namespace)::FreeTypeFont::CalcGlyphInfo(unsigned int, (anonymous namespace)::GlyphInfo&, FT_GlyphRec_*&, FT_BitmapGlyphRec_*&) ()
#6  0x00005575067ada6d in ImGuiFreeType::BuildFontAtlas(ImFontAtlas*, unsigned int) ()
#7  0x0000557506735e04 in ImGui_ImplSdlGL3_CreateFontsTexture(bool*) ()
#8  0x0000557506736258 in ImGui_ImplSdlGL3_CreateDeviceObjects(bool*) ()
#9  0x0000557506736663 in ImGui_ImplSdlGL3_NewFrame(SDL_Window*, bool*) ()
#10 0x0000557506663da4 in main ()
```

**Comment by mikesart** [comment]
Have you tried the running the imgui sdl_opengl3_example and does it have the same behavior? (Available https://github.com/ocornut/imgui)

I'll get my amd box back running and try in the next couple days as well. Thanks haasn.

**Comment by haasn** [comment]
An update: Unrelated circumstances have forced me back to the nvidia GPU / drivers, and it works again for me. I'm not sure if it was a fluke or not, but it's working now. I'll test again when I have the opportunity to switch back to mesa/amdgpu; even though I'm not entirely sure why it would be related.

(Although the whole 100% freetype CPU thing might actually be unrelated to freetype - if something about the OpenGL implementation is causing gpuvis to decide to reinitialize itself in an infinite loop)

**Comment by mikesart** [comment]
Hi haasn, if you get back to this and ever have issues, re-open this and I'll track it down. Thanks!

**Comment by haasn** [comment]
I got another chance to test this. Problem seems to have been fixed in the meantime.

**Comment by mikesart** [comment]
Good to hear. Thanks for following up haasn.
