### ISSUE TITLE
Crash as soon as a trace.dat file is read

### ISSUE THREAD

**Issue by aleixpol** [mikesart/gpuvis#34]
Using it on Plasma Wayland, not sure if it could make a difference.

Here's the example file:
https://proli.net/meu/plasma-boot/trace.dat

That's the pretty much useless backtrace it leaves behind:
```
#0  0x00007f725e1f4c87 in __strlen_avx2 () at /usr/lib/libc.so.6
#1  0x00007f725e10055e in __vfprintf_internal () at /usr/lib/libc.so.6
#2  0x00007f725e111895 in __vasprintf_internal () at /usr/lib/libc.so.6
#3  0x000055ad94c9ccda in logf(char const*, ...) ()
#4  0x000055ad94d1b0ab in  ()
#5  0x000055ad94d1d3c5 in read_trace_file(char const*, StrPool&, trace_info_t&, std::function<int (trace_event_t const&)>&) ()
#6  0x000055ad94c61225 in MainApp::thread_func(void*) ()
#7  0x00007f725e4f688f in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007f725e57eefa in  () at /usr/lib/libSDL2-2.0.so.0
#9  0x00007f725e47657f in start_thread () at /usr/lib/libpthread.so.0
#10 0x00007f725e1920e3 in clone () at /usr/lib/libc.so.6
```

Any idea what could be going on?

**Comment by mikesart** [comment]
Should be fixed. Thanks for finding and reporting this Aleix!

**Comment by aleixpol** [comment]
That's right, it's not crashing anymore, thanks! :)
