### ISSUE TITLE
i915 ctx > 0xffff

### ISSUE THREAD

**Issue by djdeath** [mikesart/gpuvis#37]
Hitting an assert when loading a trace file :
```
Thread 7 "eventloader" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff1b53700 (LWP 19292)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) refresh
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a8e535 in __GI_abort () at abort.c:79
#2  0x00007ffff7a8e40f in __assert_fail_base (fmt=0x7ffff7bf0710 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555589c38a "ctx <= 0xffff", file=0x55555589c2f8 "/home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp", line=180, function=<optimized out>) at assert.c:92
#3  0x00007ffff7a9bb92 in __GI___assert_fail (assertion=0x55555589c38a "ctx <= 0xffff", file=0x55555589c2f8 "/home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp", line=180, function=0x55555589c338 "static uint64_t TraceLocationsRingCtxSeq::db_key(uint32_t, uint32_t, const char*)") at assert.c:101
#4  0x00005555556bc77d in TraceLocationsRingCtxSeq::db_key (ringno=0, seqno=490784, ctxstr=0x7fffe045d96b "465338") at /home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp:180
#5  0x00005555556bc85c in TraceLocationsRingCtxSeq::db_key (event=...) at /home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp:204
#6  0x00005555556bc886 in TraceLocationsRingCtxSeq::add_location (this=0x555555ede920, event=...) at /home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp:213
#7  0x00005555556c236f in TraceEvents::init_i915_event (this=0x555555ede358, event=...) at /home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp:1895
#8  0x00005555556c2979 in TraceEvents::init_new_event (this=0x555555ede358, event=...) at /home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp:2043
#9  0x00005555556c2dcc in TraceEvents::init (this=0x555555ede358) at /home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp:2128
#10 0x00005555556beb74 in MainApp::thread_func (data=0x5555559a8280 <s_app()::s_app>) at /home/djdeath/src/mesa-src/gpuvis/src/gpuvis.cpp:784
#11 0x00007ffff7eb7e8c in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#12 0x00007ffff7f2b119 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#13 0x00007ffff7e32fb7 in start_thread (arg=<optimized out>) at pthread_create.c:486
#14 0x00007ffff7b6349f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Not sure how a 64bit unique id could be constructed in a different way :(

**Comment by mikesart** [comment]
Ah, interesting. You're tracing on an Intel GPU?

**Comment by djdeath** [comment]
Yep, actually trying to add an additional row with data coming from the GPU.

**Comment by djdeath** [comment]
This was easy to workaround, but not sure this is correct : https://github.com/djdeath/gpuvis/commit/39c787c33cc6cfb6430c4877cbb5018739c83f30
